### ISSUE TITLE
IOException on Dispose() method calling

### ISSUE THREAD

**Issue by sergun** [JohannesHoppe/Mongo2Go#4]
I'm trying to start Mongo2Go as following:

```csharp
 MongoDbRunner.Start(dataPath);
```

It works fine, but throws IOException on callings ```Dispose()``` method ("...unable to access local.0 file...").

At the same time ```MongoDbRunner.StartForDebugging(dataPath)``` works ok.

Looks like mongo process still running when trying to delete data files in case of ```.Start()``` method.

**Comment by Silv3rcircl3** [comment]
HI @sergun 
>MongoDbRunner.StartForDebugging(dataPath)  

didn't delete the database directory. 
You can find the sources [here](https://github.com/JohannesHoppe/Mongo2Go/blob/master/src/Mongo2Go/MongoDbRunner.IDisposable.cs)
>// will be null if we are working in debugging mode (single instance)
            if (_dataDirectoryWithPort != null)
            {
                // finally clean up the data directory we created previously
                _fileSystem.DeleteFolder(_dataDirectoryWithPort);
            }  

Are you receiving a System.UnauthorizedAccessException ?
Because I run in the same issue today with my CI-Server(Teamcity) and I had to change the folder permissions of the database directory. 
I simply granted everyone read and write access and now everything works as expected. 

Could you also try to surround the dispose call with a try catch block and check if the database directory is deleted anyway?

**Comment by JohannesHoppe** [comment]
Hmmm.... tricky one. Hard to reproduce since integrations tests work well for me.
You must have a slow machine and/or a busy MongoDB.

On https://github.com/JohannesHoppe/Mongo2Go/blob/master/src/Mongo2Go/MongoDbRunner.IDisposable.cs#L40 it tries to kill the process. I think I did the implementation a little bit wrong:

https://msdn.microsoft.com/de-de/library/system.diagnostics.process.kill(v=vs.110).aspx

> The Kill method executes asynchronously. After calling the Kill method, call the WaitForExit method to wait for the process to exit, or check the HasExited property to determine if the process has exited.

**Comment by Silv3rcircl3** [comment]
@JohannesHoppe 
it isn't that hard to reproduce ;-)

> var proc1 = Mongo2Go.MongoDbRunner.Start();
> proc1.Dispose();

write that in a console application and it will throw... 
I'm also wondering why that doesn't happen during the integration tests...
And as I mention if you surround the dispose call with a try catch the database directory is deleted anyway.

**Comment by Silv3rcircl3** [comment]
>_process.WaitForExit();

Will fix it.

**Comment by JohannesHoppe** [comment]
Excellent. This should be your release! :smile:

**Comment by Silv3rcircl3** [comment]
Alright, I will also update the MongoDB binaries to the latest version.

**Comment by JohannesHoppe** [comment]
:+1:

**Comment by JohannesHoppe** [comment]
In your nuspec you forgot one place:
https://github.com/JohannesHoppe/Mongo2Go/commit/eb7f624af038b92810248511831d9db25a474edd

**Comment by Silv3rcircl3** [comment]
Thanks.

**Comment by Silv3rcircl3** [comment]
Done :smile: 
The new version is also available on nuget.

**Comment by JohannesHoppe** [comment]
Flawless victory! :+1:
